name: Mi Laboratorio con Dominio Fijo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae tus archivos como siempre
      - name: Descargar mis archivos
        uses: actions/checkout@v4

      # 2. Instala y prepara el servidor SSH
      - name: Configurar Servidor SSH
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-server
          sudo useradd -m runner
          echo "runner:runner" | sudo chpasswd
          sudo usermod -aG sudo runner
          sudo service ssh start

      # 3. Configura y lanza el túnel Ngrok (¡CON LA LÍNEA CORREGIDA!)
      - name: Iniciar Túnel Ngrok
        uses: christianlempa/ngrok-action@v2
        with:
          port: 22
          authtoken: 32J94PqTyY3gqdd30p1zfcXqLDp_7dEgKrE4n5mgeAC2pjA4z

      # 4. Mantiene la VPS viva
      - name: Mantener viva la conexión
        run: sleep 21000
